# Generated by Django 4.0.6 on 2022-07-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=70)),
                ('liked_by', models.CharField(max_length=50)),
            ],
        ),
    ]
